/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRegressionRouteImport } from './routes/_app.regression'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppExecutionRouteImport } from './routes/_app.execution'
import { Route as AppDefectsRouteImport } from './routes/_app.defects'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiGenerationRouteImport } from './routes/_app.ai-generation'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects_.$projectId'
import { Route as AppAiGenerationBackupRouteImport } from './routes/_app.ai-generation.backup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegressionRoute = AppRegressionRouteImport.update({
  id: '/regression',
  path: '/regression',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionRoute = AppExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => AppRoute,
} as any)
const AppDefectsRoute = AppDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGenerationRoute = AppAiGenerationRouteImport.update({
  id: '/ai-generation',
  path: '/ai-generation',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppAiGenerationBackupRoute = AppAiGenerationBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppAiGenerationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-generation': typeof AppAiGenerationRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/defects': typeof AppDefectsRoute
  '/execution': typeof AppExecutionRoute
  '/projects': typeof AppProjectsRoute
  '/regression': typeof AppRegressionRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/ai-generation/backup': typeof AppAiGenerationBackupRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-generation': typeof AppAiGenerationRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/defects': typeof AppDefectsRoute
  '/execution': typeof AppExecutionRoute
  '/projects': typeof AppProjectsRoute
  '/regression': typeof AppRegressionRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/ai-generation/backup': typeof AppAiGenerationBackupRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-generation': typeof AppAiGenerationRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/defects': typeof AppDefectsRoute
  '/_app/execution': typeof AppExecutionRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/regression': typeof AppRegressionRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/ai-generation/backup': typeof AppAiGenerationBackupRoute
  '/_app/projects_/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-generation'
    | '/dashboard'
    | '/defects'
    | '/execution'
    | '/projects'
    | '/regression'
    | '/reports'
    | '/settings'
    | '/ai-generation/backup'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-generation'
    | '/dashboard'
    | '/defects'
    | '/execution'
    | '/projects'
    | '/regression'
    | '/reports'
    | '/settings'
    | '/ai-generation/backup'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-generation'
    | '/_app/dashboard'
    | '/_app/defects'
    | '/_app/execution'
    | '/_app/projects'
    | '/_app/regression'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/ai-generation/backup'
    | '/_app/projects_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regression': {
      id: '/_app/regression'
      path: '/regression'
      fullPath: '/regression'
      preLoaderRoute: typeof AppRegressionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/execution': {
      id: '/_app/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof AppExecutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/defects': {
      id: '/_app/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof AppDefectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-generation': {
      id: '/_app/ai-generation'
      path: '/ai-generation'
      fullPath: '/ai-generation'
      preLoaderRoute: typeof AppAiGenerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects_/$projectId': {
      id: '/_app/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-generation/backup': {
      id: '/_app/ai-generation/backup'
      path: '/backup'
      fullPath: '/ai-generation/backup'
      preLoaderRoute: typeof AppAiGenerationBackupRouteImport
      parentRoute: typeof AppAiGenerationRoute
    }
  }
}

interface AppAiGenerationRouteChildren {
  AppAiGenerationBackupRoute: typeof AppAiGenerationBackupRoute
}

const AppAiGenerationRouteChildren: AppAiGenerationRouteChildren = {
  AppAiGenerationBackupRoute: AppAiGenerationBackupRoute,
}

const AppAiGenerationRouteWithChildren = AppAiGenerationRoute._addFileChildren(
  AppAiGenerationRouteChildren,
)

interface AppRouteChildren {
  AppAiGenerationRoute: typeof AppAiGenerationRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDefectsRoute: typeof AppDefectsRoute
  AppExecutionRoute: typeof AppExecutionRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRegressionRoute: typeof AppRegressionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiGenerationRoute: AppAiGenerationRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDefectsRoute: AppDefectsRoute,
  AppExecutionRoute: AppExecutionRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRegressionRoute: AppRegressionRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
